# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc831a59ca1a65ec81fc213aacda615d35e4f91d9bb7530aad6488138eeb32a2544a6cc81fd5cb8cc9be4afeb2419c99fd0bc4600da4c88b5633d274b4cb496f

test:
  secret_key_base: f7e6cb81fa512c5f5778a9e1ad930617531e512e4aa89dfcc99b360cf99d17abf5a2c7b8c9f804f845f7e6a7083870f55d966d73ee70a87874ec658a51632424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
